baseURL = "https://prima2021.primamath.org/"
languageCode = "en-us"
title = "Pacific Rim Mathematical Association Congress 2021"
theme = "infinity-hugo"

[params]
  [params.hero]
    enable         = true
    bg             = "images/vancouver-bg-dark.jpg"
    title          = "PRIMA Congress 2021"
    subtitle       = "The Pacific Rim Mathematical Association Congress 2021 will take place in Vancouver, Canada in the summer of 2021. Mathematicians from around the Pacific Rim will converge to discuss the latest developments in Mathematics."
    countdownYear  = "2021"
    countdownMonth = "06"
    countdownDay   = "4"

  [params.navigation]
    logo           = "images/prima_logo_24.png"
    home           = "Home"
    about          = "About"
    speakers       = "Speakers"
    registration   = "Registration"
    organizers     = "Organizers"
    contact        = "Contact"

  [params.about]
    enable         = true
    heading        = "PRIMA 2021 - Vancouver"
    description    = "PRIMA is an association of mathematical science institutes, departments and societies from around the Pacific Rim, founded in 2005 to promote and facilitate the development of the mathematical sciences throughout the pacific rim region. The PRIMA congress is a triennial meeting of these groups which showcases recent developments in mathematics and brings together the pacific rim mathematical community."
    [[params.about.sliderItem]]
      image   = "images/1_sm.jpg"
    [[params.about.sliderItem]]
      image   = "images/2_sm.jpg"
    [[params.about.sliderItem]]
      image   = "images/3_sm.jpg"

  [params.registration]
    enable         = true
    heading        = "Registration"
    description    = "links to the registration site will be posted here when available."
  
  [params.speakers]
    enable         = true
    title          = "Speakers"
    subtitle       = "The program for this event is still being developed"
    [[params.speakers.speakerItem]]
      icon         = ""
      title        = "Speaker 1"
      description  = "Profile of speaker 1"
    [[params.speakers.speakerItem]]
      icon         = ""
      title        = "Speaker 2"
      description  = "Profile of speaker 2"
    [[params.speakers.speakerItem]]
      icon         = ""
      title        = "Speaker 3"
      description  = "Profile of speaker 3"
    [[params.speakers.speakerItem]]
      icon         = ""
      title        = "Speaker 4"
      description  = "Profile of speaker 4"
    [[params.speakers.speakerItem]]
      icon         = ""
      title        = "Speaker"
      description  = "Profile of speaker 5"


  [params.organizers]
    enable         = true
    title          = "Organizing Committee"
    subtitle       = "Members of the organizing committees will appear here soon."
    [[params.organizers.organizerItem]]
      icon         = ""
      title        = "Organizer1"
      description  = "Description of organizer 1"
    [[params.organizers.organizerItem]]
      icon         = ""
      title        = "Organizer2"
      description  = "Description of organizer 2"

  [params.contact]
    enable         = true
    title          = "Get in Touch"
    subtitle       = "If you have questions about PRIMA 2021, please get in touch with the organizing committee via the form below."

