baseURL = "https://prima2022.primamath.org/"
languageCode = "en-us"
title = "Pacific Rim Mathematical Association Congress 2022"
theme = "infinity-hugo"

[params]
  [params.hero]
    enable         = true
    bg             = "images/vancouver-winter-1900x1250-dark-reduced.jpg"
    title          = "PRIMA Congress 2022"
    subtitle       = """The 2022 Pacific Rim Mathematical Association Congress will
be take place in Vancouver, Canada, between December 4-9, 2022. The fourth
meeting will be hosted by the [Pacific Institute for the Mathematical
Sciences (PIMS)](https://www.pims.math.ca).


Every four years, mathematical scientists from around the Pacific Rim converge
to discuss the latest developments in Mathematics. The Pacific Rim Mathematical
Association (PRIMA) was established to bring a well coordinated and concerted
effort among our institutions and countries to stimulate a vibrant and
interconnected mathematical community whose activities have an unprecedented
impact on our economic, social, and cultural development."""
    countdownYear  = "2022"
    countdownMonth = "12"
    countdownDay   = "4"

  [params.navigation]
    logo           = "images/prima_logo_24.png"
    home           = "Home"
    about          = "About"
    schools        = "Summer Schools"
    speakers       = "Speakers"
    organizers     = "Organizers"
    sessions       = "Sessions"
    calendar       = "Calendar"
    registration   = "Registration"
    localinfo      = "Local Information"
    sponsors       = "Sponsors"
    contact        = "Contact"

  [params.schools]
    enable         = true
    heading        = "PRIMA 2022 Summer Schools"
    description    = """
"""

  [params.about]
    enable         = false
    heading        = "PRIMA 2022 - Vancouver"
    description    = "PRIMA is an association of mathematical science institutes, departments and societies from around the Pacific Rim, founded in 2005 to promote and facilitate the development of the mathematical sciences throughout the pacific rim region. The PRIMA congress is a triennial meeting of these groups which showcases recent developments in mathematics and brings together the pacific rim mathematical community."
    [[params.about.sliderItem]]
      imageWebp   = "images/1_sm.webp"
      imageJpeg   = "images/1_sm.jpg"
      credit       = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = "images/2_sm.webp"
      imageJpeg   = "images/2_sm.jpg"
      credit       = 'Tourism Vancouver / Kazutoshi Yoshimura'
    [[params.about.sliderItem]]
      imageWebp   = "images/3_sm.webp"
      imageJpeg   = "images/3_sm.jpg"
      credit       = 'Tourism Vancouver / Albert Normandin'
    [[params.about.sliderItem]]
      imageWebp   = 'images/4_sm.webp'
      imageJpeg   = 'images/4_sm.jpg'
      credit  = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = 'images/5_sm.webp'
      imageJpeg   = 'images/5_sm.jpg'
      credit  = 'Tourism Vancouver / Avision Photography by Chris Collacott'

  [params.calendar]
    enable         = true
    heading        = "Calendar"
    description    = """\
<div>
  <div title="Whova event and conference app" id="whova-agendawidget">
    <p id="whova-loading">Loading...</p>
  </div>
  <script src="https://whova.com/static/frontend/xems/js/embed/embedagenda.js?eid=ADY6gBK9ICX6pYBVpBvTmrvfl1jm1IzkgYsX7t2QmxE%3D&host=https://whova.com" type="text/javascript"  id="embeded-agenda-script"></script>
</div>
"""
  [params.registration]
    enable         = true
    heading        = "Registration"
    description    = """\
<div id="whova-regform-widget"></div><script src="https://whova.com/static/frontend/xems/js/whova-regform-widget.js?eid=prima_202204&host=https://whova.com&registration=exhibitor" type="text/javascript" id="whova-embeded-regform-script"></script>
"""

  [params.localinfo]
    enable         = true
    heading        = "Local Information"
    content    = """\
PRIMA 2022 should be a safe and enjoyable for all participants. As such, we
will be following guidance and restrictions from the Province of British
Columbia and the Federal Government of Canada around COVID-19.


#### Restrictions
  * We encourage participants to be fully vaccinated prior to PRIMA 2022
  * We encourage particpants to wear masks in all indoor shared spaces
  * The Canadian Government requires that **_ALL_** international participants **_must_** complete the [ArriveCan](https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19/arrivecan.html) process prior to arriving in Canada. This restriction applies at all border crossings, including the land crossing from the United States.

#### Additional Information
  * [Canadian Federal Government COVID 19 Travel Information](https://travel.gc.ca/travel-covid).  Please note, _**ALL**_ international participants **_must_** complete the [ArriveCan](https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19/arrivecan.html) process prior to travelling to Canada.
  * [Public Health Agency of Canada](https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19.html) - Information from the Canadian Federal Government about COVID-19
  * [BC Centre for Disease Control](http://www.bccdc.ca/health-info/diseases-conditions/covid-19/event-planning) - Information from the BC Center for Disease Control about indoor events
  * [BC Provincial Health Officer](https://www2.gov.bc.ca/gov/content/health/about-bc-s-health-care-system/office-of-the-provincial-health-officer/current-health-topics/covid-19-novel-coronavirus) - Information about the Province of British Columbia's COVID-19 response and restrictions.
"""


  [params.sessions]
    enable         = true
    title          = "Special Sessions"
    description    = """

## Early Career Research Showcase

The PRIMA Early Career Researcher's Showcase is a short session for early career
participants (undergraduate, graduate and postdoctoral scholars) to highlight
their areas of research. This can be done either through the poster session, or
a 10 minute presentation.

Research topics are open, but should focus on the presenters area of research.
Presentations cannot highlight open or exploratory material. Please fill in the
[application form](https://ubc.ca1.qualtrics.com/jfe/form/SV_3qLmqRb4Je6a8Pc) with the poster/ talk details. Submissions close **June 30th, 2022**.


## Scientific Sessions


#### Algebraic Number Theory and Arithmetic Geometry

##### Organizers
  * Ellen Eischen, _University of Oregon_
  * Sug Woo Shin, _University of California - Berkeley_
  * Liang Xiao, _Peking University_


#### Arithmetic Geometry: Theory and Computation

##### Organizers
  * Bianca Viray, _University of Washington_
  * Sho Tanimoto, _Nagoya University_


#### Enumerative Algebraic Geometry

##### Organizers
  * Huai-Liang Chang, _Hong Kong University of Science and Technology_
  * Wei-Ping Li, _Hong Kong University of Science and Technology_
  * Junwu Tu, _Shanghai Tech University_


#### Geometric Analysis

##### Organizers
  * Otis Chodosh, _Stanford University_
  * Mariel Saez, _Universidad Católica de Chile_
  * Yoshi Tonegawa, _Tokyo Institute of Technology_
  * Raquel Perales, _Universidad Nacional Autónoma de México_


#### Geometric Group Theory

##### Organizers
  * Mladen Bestvina, _University of Utah_
  * Rita Jimenez Rolland, _Universidad Nacional Autónoma de México_
  * Koji Fujiwara, _Kyoto University_
  * Priyam Patel, _University of Utah_
  * Jesus Hernandez Hernandez _Universidad Nacional Autónoma de México_


#### Graph Theory and Combinatorics

##### Organizers
  * Bojan Mohar, _Simon Fraser University_
  * Karen Meagher, _University of Regina_
  * Karen Gunderson _University of Manitoba_
  * Joy Morris, _University of Lethbridge_


#### Harmonic Functions and Laplace Eigenfunctions

##### Organizers
  * Eugenia Malinnikova, _Stanford University_
  * Bobby Wilson, _University of Washington_
  * Zihui Zhao, _University of Chicago_


#### Indigenous Mathematical Scientists

##### Organizers
  *  Kamuela Yong, _University of Hawai'i - West O'ahu_


#### Mathematics of Infectious Disease Modelling

##### Organizers
  * Caroline Colijn, _Simon Fraser University_
  * Siva Athreya, _Indian Statistical Institute_
  * Abraham D. Flaxman, _University of Washington_


#### Mathematics of Information

##### Organizers
  * Rayan Saab, _University of California, San Diego_
  * Mark Iwen, _Michigan State University_


#### Moduli Spaces in Algebraic Geometry

##### Organizers
  * Alexander Polishchuk, _University of Oregon_
  * Nicolas Addington, _University of Oregon_


#### New Trends in Geometry and Mathematical Physics

##### Organizers
  * Vincent Bouchard, _University of Alberta_
  * Norman Do, _Monash University_
  * Steven Rayan _University of Saskatchewan_
  * Thomas Creutzig, _University of Alberta_


#### Optimal Transport and Applications

##### Organizers
  * Shibing Chen, _University of Science and Technology of China_
  * Young-Heon Kim, _University of British Columbia_
  * Soumik Pal, _University of Washington_
  * Brendan Pass, _University of Alberta_
  * Asuka Takatsu, _Tokyo Metropolitan University_


#### Representation Theory and Applications

##### Organizers
  * Robert M. Guralnick, _University of South Carolina_
  * Arun Ram, _University of Melbourne_
  * Pham H. Tiep _Rutgers University_



## Summer Schools

A number of summer schools will be run in advance of PRIMA 2022, please see the
individual summer school pages for more details and to register.

#### Summer School in Arithmetic Geometry: Theory and Computation

##### August 2nd-4th, 2021

In advance of PRIMA 2022, a number of summer schools will take place prior to
the main event at the end of the year. The first summer school on [Arithmetic
Geometry: Theory and
Computation](https://www.pims.math.ca/scientific-event/210802-pssrcmsag) will
take place **August 2-4th, 2021**. Please see the [event
webpage](https://www.pims.math.ca/scientific-event/210802-pssrcmsag) for more
information and to register.
"""

  [params.speakers]
    enable         = true
    title          = "Speakers"
    subtitle       = ""
    more           = "See all speakers"

  [params.organizers]
    enable         = true
    title          = "Organizing Committee"
    subtitle       = ""
    more           = "See all organizers"

  [params.contact]
    enable             = true
    title              = "Contact"
    title_mailchimp    = "Mailing List"
    subtitle_mailchimp = "To receive the latest updates from PRIMA 2022, including registration details, please sign up for our newsletter."
    title_form         = "Have a question?"
    subtitle_form      = "If you have questions about PRIMA 2022, please get in touch with the organizing committee via the form below."


  [params.sponsors]
  enable = true
  title  = "Sponsors"
  subtitle = "PRIMA 2022 gratefully acknowledges the following sponsors. To learn more about sponsorship opportunities, please see our [Sponsor Package](uploads/PRIMA2022SponsorPackage.pdf), or contact us directly at events@pims.math.ca"
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/QAI.svg"
  url = 'https://quantumalgorithms.ca/'
  title_sponsor = true
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/PIMS-logo-full.svg"
  url   = 'https://www.pims.math.ca'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/CMS-logo.png"
  url   = 'https://cms.math.ca/'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/MSRI-logo.png"
  url   = 'https://www.msri.org/'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/Simons.png"
  url   = 'https://www.simonsfoundation.org/'
 

[taxonomies]
  category = "categories"
  tags = "tags"
  committees = "committees"
  speakertype = "speakertype"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
