baseURL = "https://prima2022.primamath.org/"
languageCode = "en-us"
title = "Pacific Rim Mathematical Association Congress 2022"
theme = "infinity-hugo"

[params]
  [params.hero]
    enable         = true
    bg             = "images/vancouver-winter-1900x1250-dark-reduced.jpg"
    title          = "PRIMA Congress 2022"
    subtitle       = "The Pacific Rim Mathematical Association Congress 2022 will be hosted by the [Pacific Institute for the Mathematical Sciences](https://www.pims.math.ca) and will take place in Vancouver, Canada between December 4-9, 2022. Mathematical Scientists from around the Pacific Rim will converge to discuss the latest developments in Mathematics"
    countdownYear  = "2022"
    countdownMonth = "12"
    countdownDay   = "4"

  [params.navigation]
    logo           = "images/prima_logo_24.png"
    home           = "Home"
    about          = "About"
    schools        = "Summer Schools"
    speakers       = "Speakers"
    organizers     = "Organizers"
    sessions       = "Sessions"
    registration   = "Registration"
    sponsors       = "Sponsors"
    contact        = "Contact"

  [params.schools]
    enable         = true
    heading        = "PRIMA 2022 Summer Schools"
    description    = """
"""

  [params.about]
    enable         = false
    heading        = "PRIMA 2022 - Vancouver"
    description    = "PRIMA is an association of mathematical science institutes, departments and societies from around the Pacific Rim, founded in 2005 to promote and facilitate the development of the mathematical sciences throughout the pacific rim region. The PRIMA congress is a triennial meeting of these groups which showcases recent developments in mathematics and brings together the pacific rim mathematical community."
    [[params.about.sliderItem]]
      imageWebp   = "images/1_sm.webp"
      imageJpeg   = "images/1_sm.jpg"
      credit       = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = "images/2_sm.webp"
      imageJpeg   = "images/2_sm.jpg"
      credit       = 'Tourism Vancouver / Kazutoshi Yoshimura'
    [[params.about.sliderItem]]
      imageWebp   = "images/3_sm.webp"
      imageJpeg   = "images/3_sm.jpg"
      credit       = 'Tourism Vancouver / Albert Normandin'
    [[params.about.sliderItem]]
      imageWebp   = 'images/4_sm.webp'
      imageJpeg   = 'images/4_sm.jpg'
      credit  = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = 'images/5_sm.webp'
      imageJpeg   = 'images/5_sm.jpg'
      credit  = 'Tourism Vancouver / Avision Photography by Chris Collacott'

  [params.registration]
    enable         = true
    heading        = "Registration"
    description    = "Links to the registration site will be posted here when available."

  [params.sessions]
    enable         = true
    title          = "Special Sessions"
    description    = """

## Junior Research Showcase

The PRIMA Junior Researcher's Showcase is a short session for junior
participants (undergraduate, graduate and postdoctoral scholars) to highlight
their areas of research. This can be done either through the poster session, or
a 10 minute presentation.

Research topics are open, but should focus on the presenters area of research.
Presentations cannot highlight open or exploratory material. Please fill in the
[application form](https://ubc.ca1.qualtrics.com/jfe/form/SV_3qLmqRb4Je6a8Pc) with the poster/ talk details. Submissions close **March 31st, 2022**.


## Scientific Sessions


#### Algebraic Number Theory and Arithmetic Geometry

##### Organizers
  * Ellen Eischen, _University of Oregon_
  * Sug Woo Shin, _University of California - Berkeley_
  * Liang Xiao, _Peking University_


#### Arithmetic Geometry: Theory and Computation

##### Organizers
  * Bianca Viray, _University of Washington_
  * Sho Tanimoto, _Nagoya University_


#### Enumerative Algebraic Geometry

##### Organizers
  * Huai-Liang Chang, _Hong Kong University of Science and Technology_
  * Wei-Ping Li, _Hong Kong University of Science and Technology_
  * Junwu Tu, _Shanghai Tech University_


#### Geometric Analysis

##### Organizers
  * Otis Chodosh, _Stanford University_
  * Mariel Saez, _Universidad Católica de Chile_
  * Yoshi Tonegawa, _Tokyo Institute of Technology_
  * Raquel Perales, _Universidad Nacional Autónoma de México_


#### Geometric Group Theory

##### Organizers
  * Mladen Bestvina, _University of Utah_
  * Rita Jimenez Rolland, _Universidad Nacional Autónoma de México_
  * Koji Fujiwara, _Kyoto University_
  * Priyam Patel, _University of Utah_
  * Jesus Hernandez Hernandez _Universidad Nacional Autónoma de México_


#### Graph Theory and Combinatorics

##### Organizers
  * Bojan Mohar, _Simon Fraser University_
  * Karen Meagher, _University of Regina_
  * Karen Gunderson _University of Manitoba_
  * Joy Morris, _University of Lethbridge_


#### Harmonic Functions and Laplace Eigenfunctions

##### Organizers
  * Eugenia Malinnikova, _Stanford University_
  * Bobby Wilson, _University of Washington_
  * Zihui Zhao, _University of Chicago_


#### Hyperbolic and Parabolic Dynamics

##### Organizers
  * Anthony Quas, _University of Victoria_
  * Cheung Yitwah, _Tsinghua University_
  * Jana Rodriguez-Hertz, _Southern University of Science and Technology_
  * Cecilia Gonzalez-Tokman, _University of Queensland_


#### Indigenous Mathematical Scientists

##### Organizers
  *  Kamuela Yong, _University of Hawai'i - West O'ahu_


#### Mathematics of Infectious Disease Modelling

##### Organizers
  * Caroline Colijn, _Simon Fraser University_
  * Siva Athreya, _Indian Statistical Institute_
  * Abraham D. Flaxman, _University of Washington_


#### Mathematics of Information

##### Organizers
  * Rayan Saab, _University of California, San Diego_
  * Mark Iwen, _Michigan State University_


#### Moduli Spaces in Algebraic Geometry

##### Organizers
  * Alexander Polishchuk, _University of Oregon_
  * Nicolas Addington, _University of Oregon_


#### New Trends in Geometry and Mathematical Physics

##### Organizers
  * Vincent Bouchard, _University of Alberta_
  * Norman Do, _Monash University_
  * Steven Rayan _University of Saskatchewan_
  * Thomas Creutzig, _University of Alberta_


#### Optimal Transport and Applications

##### Organizers
  * Shibing Chen, _University of Science and Technology of China_
  * Young-Heon Kim, _University of British Columbia_
  * Soumik Pal, _University of Washington_
  * Brendan Pass, _University of Alberta_
  * Asuka Takatsu, _Tokyo Metropolitan University_


#### Representation Theory and Applications

##### Organizers
  * Robert M. Guralnick, _University of South Carolina_
  * Arun Ram, _University of Melbourne_
  * Pham H. Tiep _Rutgers University_



## Summer Schools

A number of summer schools will be run in advance of PRIMA 2022, please see the
individual summer school pages for more details and to register.

#### Summer School in Arithmetic Geometry: Theory and Computation

##### August 2nd-4th, 2021

In advance of PRIMA 2022, a number of summer schools will take place prior to
the main event at the end of the year. The first summer school on [Arithmetic
Geometry: Theory and
Computation](https://www.pims.math.ca/scientific-event/210802-pssrcmsag) will
take place **August 2-4th, 2021**. Please see the [event
webpage](https://www.pims.math.ca/scientific-event/210802-pssrcmsag) for more
information and to register.
"""

  [params.speakers]
    enable         = true
    title          = "Speakers"
    subtitle       = ""
    more           = "See all speakers"

  [params.organizers]
    enable         = true
    title          = "Organizing Committee"
    subtitle       = ""
    more           = "See all organizers"

  [params.contact]
    enable             = true
    title              = "Contact"
    title_mailchimp    = "Mailing List"
    subtitle_mailchimp = "To receive the latest updates from PRIMA 2022, including registration details, please sign up for our newsletter."
    title_form         = "Have a question?"
    subtitle_form      = "If you have questions about PRIMA 2022, please get in touch with the organizing committee via the form below."


  [params.sponsors]
  enable = true
  title  = "Sponsors"
  subtitle = "PRIMA 2022 gratefully acknowledges the following sponors"
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/PIMS-logo-full.svg"
  url   = 'https://www.pims.math.ca'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/CMS-logo.png"
  url   = 'https://cms.math.ca/'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/MSRI-logo.png"
  url   = 'https://www.msri.org/'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/Simons.png"
  url   = 'https://www.simonsfoundation.org/'
 

[taxonomies]
  category = "categories"
  tags = "tags"
  committees = "committees"
  speakertype = "speakertype"
