baseURL = "https://prima2022.primamath.org/"
languageCode = "en-us"
title = "Pacific Rim Mathematical Association Congress 2022"
theme = "infinity-hugo"

[params]
  [params.hero]
    enable         = true
    bg             = "images/vancouver-winter-1900x1250-dark-reduced.jpg"
    title          = "PRIMA Congress 2022"
    subtitle       = "The Pacific Rim Mathematical Association Congress 2022 will take place in Vancouver, Canada between December 4-9, 2022. Mathematicians from around the Pacific Rim will converge to discuss the latest developments in Mathematics."
    countdownYear  = "2022"
    countdownMonth = "12"
    countdownDay   = "4"

  [params.navigation]
    logo           = "images/prima_logo_24.png"
    home           = "Home"
    about          = "About"
    schools        = "Summer Schools"
    speakers       = "Speakers"
    organizers     = "Organizers"
    sessions       = "Sessions"
    registration   = "Registration"
    sponsors       = "Sponsors"
    contact        = "Contact"

  [params.schools]
    enable         = true
    heading        = "PRIMA 2022 Summer Schools"
    description    = """
In advance of PRIMA 2022, a number of summer schools will take place prior to
the main event at the end of the year. The first summer school on [Arithmetic
Geometry: Theory and
Computation](https://www.pims.math.ca/scientific-event/210802-pssrcmsag) will
take place August 2-4th, 2021. Please see the [event
webpage](https://www.pims.math.ca/scientific-event/210802-pssrcmsag) for more
information and to register.
"""

  [params.about]
    enable         = false
    heading        = "PRIMA 2022 - Vancouver"
    description    = "PRIMA is an association of mathematical science institutes, departments and societies from around the Pacific Rim, founded in 2005 to promote and facilitate the development of the mathematical sciences throughout the pacific rim region. The PRIMA congress is a triennial meeting of these groups which showcases recent developments in mathematics and brings together the pacific rim mathematical community."
    [[params.about.sliderItem]]
      imageWebp   = "images/1_sm.webp"
      imageJpeg   = "images/1_sm.jpg"
      credit       = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = "images/2_sm.webp"
      imageJpeg   = "images/2_sm.jpg"
      credit       = 'Tourism Vancouver / Kazutoshi Yoshimura'
    [[params.about.sliderItem]]
      imageWebp   = "images/3_sm.webp"
      imageJpeg   = "images/3_sm.jpg"
      credit       = 'Tourism Vancouver / Albert Normandin'
    [[params.about.sliderItem]]
      imageWebp   = 'images/4_sm.webp'
      imageJpeg   = 'images/4_sm.jpg'
      credit  = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = 'images/5_sm.webp'
      imageJpeg   = 'images/5_sm.jpg'
      credit  = 'Tourism Vancouver / Avision Photography by Chris Collacott'

  [params.registration]
    enable         = true
    heading        = "Registration"
    description    = "links to the registration site will be posted here when available."

  [params.sessions]
    enable         = true
    title          = "Special Sessions"
    description    = """
PRIMA 2022 will include special sessions in the following areas

  * Arithmetic Geometry: Theory and Gomputation
  * Harmonic Functions and Laplace Eigenfunctions
  * Algebraic Number Theory and Arithmetic Geometry
  * Enumerative Algebraic Geometry
  * New Trends in Geometry and Mathematical Physics
  * Hyperbolic and Parabolic Dynamics
  * Optimal Transport and Applications
  * Low Dimensional Topology
  * Geometric Group Theory
  * Representation Theory and Applications
  * Geometric Analysis
  * Moduli Spaces in Algebraic Geometry
  * Graph Theory and Coombinatorics
  * A celebration of Indigenous mathematicians
"""

  [params.speakers]
    enable         = true
    title          = "Speakers"
    subtitle       = ""
    more           = "See all speakers"

  [params.organizers]
    enable         = true
    title          = "Organizing Committee"
    subtitle       = ""
    more           = "See all organizers"

  [params.contact]
    enable         = true
    title          = "Get in Touch"
    subtitle       = "If you have questions about PRIMA 2022, please get in touch with the organizing committee via the form below."

  [params.sponsors]
  enable = true
  title  = "Sponsors"
  subtitle = "PRIMA 2022 gratefully acknowledges the following sponors"
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/CMS-logo.png"
  url   = 'https://cms.math.ca/'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/PIMS-logo.png"
  url   = 'https://www.pims.math.ca'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/MSRI-logo.png"
  url   = 'https://www.msri.org/'

[taxonomies]
  category = "categories"
  tags = "tags"
  committees = "committees"
  speakers = "speakers"
