baseURL = "https://prima2021.primamath.org/"
languageCode = "en-us"
title = "Pacific Rim Mathematical Association Congress 2021"
theme = "infinity-hugo"

[params]
  [params.hero]
    enable         = true
    bg             = "images/vancouver-winter-1900x1250-dark.webp"
    title          = "PRIMA Congress 2021"
    subtitle       = "The Pacific Rim Mathematical Association Congress 2021 will take place in Vancouver, Canada between December 5-10, 2021. Mathematicians from around the Pacific Rim will converge to discuss the latest developments in Mathematics."
    countdownYear  = "2021"
    countdownMonth = "12"
    countdownDay   = "5"

  [params.navigation]
    logo           = "images/prima_logo_24.png"
    home           = "Home"
    about          = "About"
    organizers     = "Organizers"
    registration   = "Registration"
    sponsors       = "Sponsors"
    contact        = "Contact"

  [params.about]
    enable         = true
    heading        = "PRIMA 2021 - Vancouver"
    description    = "PRIMA is an association of mathematical science institutes, departments and societies from around the Pacific Rim, founded in 2005 to promote and facilitate the development of the mathematical sciences throughout the pacific rim region. The PRIMA congress is a triennial meeting of these groups which showcases recent developments in mathematics and brings together the pacific rim mathematical community."
    [[params.about.sliderItem]]
      imageWebp   = "images/1_sm.webp"
      imageJpeg   = "images/1_sm.jpg"
      credit       = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = "images/2_sm.webp"
      imageJpeg   = "images/2_sm.jpg"
      credit       = 'Tourism Vancouver / Kazutoshi Yoshimura'
    [[params.about.sliderItem]]
      imageWebp   = "images/3_sm.webp"
      imageJpeg   = "images/3_sm.jpg"
      credit       = 'Tourism Vancouver / Albert Normandin'
    [[params.about.sliderItem]]
      imageWebp   = 'images/4_sm.webp'
      imageJpeg   = 'images/4_sm.jpg'
      credit  = 'Tourism Vancouver / Clayton Perry'
    [[params.about.sliderItem]]
      imageWebp   = 'images/5_sm.webp'
      imageJpeg   = 'images/5_sm.jpg'
      credit  = 'Tourism Vancouver / Avision Photography by Chris Collacott'

  [params.registration]
    enable         = true
    heading        = "Registration"
    description    = "links to the registration site will be posted here when available."
  
  [params.organizers]
    enable         = true
    title          = "Organizing Committee"
    subtitle       = "Members of the organizing committees will appear here soon."
    more           = "See all organizers"

  [params.contact]
    enable         = true
    title          = "Get in Touch"
    subtitle       = "If you have questions about PRIMA 2021, please get in touch with the organizing committee via the form below."

  [params.sponsors]
  enable = true
  title  = "Sponsors"
  subtitle = "PRIMA 2021 gratefully acknowledges the following sponors"
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/CMS-logo.png"
  url   = 'https://cms.math.ca/'
  [[params.sponsor.sponsorItem]]
  image = "images/sponsor/PIMS-logo.png"
  url   = 'https://www.pims.math.ca'
