---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/organizers
  label: Organizers
  create: all
  match: "**/*"
  templates:
  - speakers
- type: directory
  path: content/speakers
  label: Speakers
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - speakers
- type: heading
  label: Front Page
- type: document
  path: config.toml
  label: Config
- type: heading
  label: Other
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.1
